### ISSUE TITLE
Provide txn IR for debugging upon failure

### ISSUE THREAD

**Issue by Nashtare** [0xPolygonZero/zero-bin#11]
We currently only have access in the logs to the proving trace upon failure.

It would be nice to also log
- the `GenerationInputs` payload passed to `generate_txn_proof()` (to be able to regenerate locally easily when debugging)
- the `PublicValues` associated to the `AggregatableProof` LHS and RHS arguments of `generate_agg_proof()`, and the ones for previous block proof and current one in `generate_block_proof()`

**Comment by vladimir-trifonov** [comment]
The first one should be fixed in:
https://github.com/0xPolygonZero/zk_evm/blob/81b5ef2088e4707ee173f8eea95e50b96237a227/evm_arithmetization/src/generation/mod.rs#L225 as part of evm_arithmetization v0.1.2.

About the second: https://github.com/0xPolygonZero/zk_evm/pull/134

**Comment by Nashtare** [comment]
I may have badly phrased it when writing the issue, but rather than logging, I really meant writing to disk the related components. Logs are usually pretty noisy already, and with real states generating pretty large partial tries pre-txn, it's impossible to easily extract from log outputs stuff like generation inputs for instance.

Public Values on the other hand are always limited in size (though the vector of previous block hashes is on its own a bit large and noisy to print), but are sufficiently small to be only part of the logging output.

**Comment by vladimir-trifonov** [comment]
@Nashtare https://github.com/0xPolygonZero/zero-bin/pull/48
