### ISSUE TITLE
Address unimplemented `resolve_code_hash_fn`

### ISSUE THREAD

**Issue by Nashtare** [0xPolygonZero/zero-bin#38]
This leads to proving failures for 34 out of the 700 blocks sequence on the hard test chain.

@BGluth assigning it to you as I think you had already dealt with it somewhere?

**Comment by BGluth** [comment]
Yeah currently taking a look at this. Once things settle down I'll merge in my logic to detect missing code hashes right after decoding the incoming compact.

Note that if the compact does not contain code for a referenced code hash that it will hit this `todo`, and I'll know pretty soon if this is the case.

**Comment by Nashtare** [comment]
Solved on jerigon's side.
