### ISSUE TITLE
Introduce block intervals to zero-bin

### ISSUE THREAD

**Issue by atanmarko** [0xPolygonZero/zero-bin#87]
We need to unify `zero-bin` program input to handle one, multiple blocks, or continuous stream of new blocks, as discussed in https://github.com/0xPolygonZero/zero-bin/issues/86. Introduce new type `BlockInterval` as a CLI argument, and update API of the main use-cases to use it.

Also, introduce new parameter that would indicate if the blocks in the range are dependent from previous block proof. If they are not dependent, their proof generation could be fully parallelized in some future PR.

**Comment by Nashtare** [comment]
> If they are not dependent, their proof generation could be fully parallelized in some future PR.

Only the final layer (eg `prove_block`) can be requiring the previous block proof. So we could still have almost full concurrency across consecutive blocks, by treating all txn / aggregation proofs in parallel. Only the final proof (block) would be pending completion of the previous block.

**Comment by atanmarko** [comment]
> > If they are not dependent, their proof generation could be fully parallelized in some future PR.
> 
> Only the final layer (eg `prove_block`) can be requiring the previous block proof. So we could still have almost full concurrency across consecutive blocks, by treating all txn / aggregation proofs in parallel. Only the final proof (block) would be pending completion of the previous block.

Right, tasks https://github.com/0xPolygonZero/zero-bin/issues/88 and https://github.com/0xPolygonZero/zero-bin/issues/89 should address that topic
